import { Metadata } from 'next'
import 'src/app/styles/globals.css'

export const metadata: Metadata = {
  title: 'NoowaH Blog',
  description: 'Generated by create next app'
}

interface Params {
  children: React.ReactNode
}

const RootLayout = ({ children }: Params) => {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}

export default RootLayout
