import { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'NoowaH Blog',
  description: 'Generated by create next app'
}

interface Params {
  children: React.ReactNode
}

const RootLayout = ({ children }: Params) => {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}

export default RootLayout
