name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create Release Drafter
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          version: ${{ github.ref_name }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
