name: Create Release

on:
  push:
    tags:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  create-release-draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
          version: ${{ github.ref_name }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
