name: Create Tag

on:
  push:
    branches:
      - dev

jobs:
  create-tag:
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    steps:
      # - uses: actions/checkout@v3
      # # Creates Tag using automated changelogs
      # # conventional commit
      # # - `feat:` -> increments the middle digit  `0.1.0`
      # # - `fix:` -> increments the last digit `0.0.1`
      # - name: Conventional Changelog Action
      #   id: changelog
      #   uses: TriPSs/conventional-changelog-action@v3.19.0
      #   with:
      #     github-token: ${{ secrets.github_token }}
      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Create Draft
        id: release_drafter
        uses: ./.github/release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ github.ref_name }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
