name: Create Release

on:
  push:
    tags:
      # v1.0.0
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # v1.0.0-alpha.1
      - '!v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+.[0-9]+'
jobs:
  release:
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo $VERSION
          echo "::set-output name=version::$VERSION"

      - name: Create Draft
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          version: ${{ steps.get_version.outputs.version }}
          publish: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
