name: Release

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Latest Tag
        id: get_latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)  
          CHANGELOG=$(git log --format=%B ${LATEST_TAG}..HEAD)
          echo "::set-output name=changelog::$CHANGELOG"

      - name: Display Changelog
        run: |
          echo "Changelog: ${{ steps.get_changelog.outputs.changelog }}"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.19.0
        with:
          github-token: ${{ secrets.github_token }}
          output-file: 'false'

      # Create a release after creating tag
      # - only create a release if there is change of tags
      - name: create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
